[ImportFolders]
; Rutas de las carpetas de entrada de documentos
; Hay que indicar el número de carpetas que hay que monitorizar,
; y crear una sección para cada una de ellas con el numerador correspondiente.
Count=3
Folder1=C:\Tecnomedia Sistemas\ProyectoAutorizaciones\Entrada\Facturas
Folder2=C:\Tecnomedia Sistemas\ProyectoAutorizaciones\Entrada\Autorizaciones
Folder3=C:\Tecnomedia Sistemas\ProyectoAutorizaciones\Entrada\Informes

[Service]
; Número de segundos de espera para comprobar que el archivo PDF se ha copiado completamente antes de procesarlo
DelaySeconds=30

; Ruta de la carpeta de log
[Logging]
Path=C:\Tecnomedia Sistemas\ProyectoAutorizaciones\Log
