[ImportFolders]
Facturas=C:\Tecnomedia Sistemas\ProyectoAutorizaciones\Entrada\Facturas
;Facturas=Z:\FACTURACION\DOCUMENTACION MUTUA\WINDREAM\FACTURAS
FacturasProcessed=C:\Tecnomedia Sistemas\ProyectoAutorizaciones\Procesados\Facturas
FacturasIncidencias=C:\Tecnomedia Sistemas\ProyectoAutorizaciones\Inicidencias\Facturas
Autorizaciones=C:\Tecnomedia Sistemas\ProyectoAutorizaciones\Entrada\Autorizaciones
;Autorizaciones=Z:\AUTORIZACIONES
AutorizacionesProcessed=C:\Tecnomedia Sistemas\ProyectoAutorizaciones\Procesados\Autorizaciones
AutorizacionesIncidencias=C:\Tecnomedia Sistemas\ProyectoAutorizaciones\Inicidencias\Autorizaciones
Informes=C:\Tecnomedia Sistemas\ProyectoAutorizaciones\Entrada\Informes
;Informes=Z:\FACTURACION\DOCUMENTACION MUTUA\WINDREAM\INFORMES
InformesProcessed=C:\Tecnomedia Sistemas\ProyectoAutorizaciones\Procesados\Informes
InformesIncidencias=C:\Tecnomedia Sistemas\ProyectoAutorizaciones\Inicidencias\Informes

[Service]
; Número de segundos de espera para comprobar que el archivo PDF se ha copiado completamente antes de procesarlo
DelaySeconds=30
PathTemplateFactura=C:\Tecnomedia Sistemas\ProyectoAutorizaciones\Fuentes\SF_DocImporter\PdfProcessingService\Templates\TemplateFactura.json
PathMutuas=C:\Tecnomedia Sistemas\ProyectoAutorizaciones\Fuentes\SF_DocImporter\PdfProcessingService\mutuas.txt

; Valor máximo de la distancia Levensthein que aceptamos como diferencia de cobertura en factura
MaxLevensthein=3

; Ruta de la carpeta de log
[Logging]
Path=C:\Tecnomedia Sistemas\ProyectoAutorizaciones\Log

[Windream]
Path=Expedientes
ObjectType=Expediente
; Número de meses que el documento estará disponible. Si ponemos un 0, el documento no se borrará nunca
MesesArchivo=60