[ImportFolders]
; Rutas de las carpetas de entrada de documentos
; Hay que indicar el número de carpetas que hay que monitorizar,
; y crear una sección para cada una de ellas con el numerador correspondiente.
Count=3
Folder1=C:\Tecnomedia Sistemas\ProyectoAutorizaciones\Entrada\Facturas
FolderProcessed1=C:\Tecnomedia Sistemas\ProyectoAutorizaciones\Procesados\Facturas
FolderIncidencias1=C:\Tecnomedia Sistemas\ProyectoAutorizaciones\Inicidencias\Facturas
Folder2=C:\Tecnomedia Sistemas\ProyectoAutorizaciones\Entrada\Autorizaciones
FolderProcessed2=C:\Tecnomedia Sistemas\ProyectoAutorizaciones\Procesados\Autorizaciones
FolderIncidencias2=C:\Tecnomedia Sistemas\ProyectoAutorizaciones\Inicidencias\Autorizaciones
Folder3=C:\Tecnomedia Sistemas\ProyectoAutorizaciones\Entrada\Informes
FolderProcessed3=C:\Tecnomedia Sistemas\ProyectoAutorizaciones\Procesados\Informes
FolderIncidencias3=C:\Tecnomedia Sistemas\ProyectoAutorizaciones\Inicidencias\Informes

[Service]
; Número de segundos de espera para comprobar que el archivo PDF se ha copiado completamente antes de procesarlo
DelaySeconds=30

; Valor máximo de la distancia Levensthein que aceptamos como diferencia de cobertura en factura
MaxLevensthein=3

; Ruta de la carpeta de log
[Logging]
Path=C:\Tecnomedia Sistemas\ProyectoAutorizaciones\Log

[Windream]
Path=Expedientes
ObjectType=Expediente
; Número de meses que el documento estará disponible. Si ponemos un 0, el documento no se borrará nunca
MesesArchivo=60