[Windream]
; Si no hay unidad de red indicada, busca en la ruta \\Windream\Objects
UnidadRed=
ObjectType=Expediente

[Mutuas]
Path=C:\Tecnomedia Sistemas\ProyectoAutorizaciones\Fuentes\SF_DocImporter\GestorExpedientesWpf\mutuas.txt